from django.conf.urls import patterns, url, include
from aloha import views

urlpatterns = patterns('',
    url(r'^$',
        views.index, 
        name='index'),
    url(r'create_user/$',
        views.create_user,
        name='create_user'),
    url(r'dashboard/$',
        views.dashboard,
        name='dashboard'),
    url(r'login_page/$',
        views.login_page,
        name='login_page'),
    url(r'logout_page/$',
        views.logout_page,
        name='logout_page'),
    url(r'privacy/$',
        views.privacy,
        name='privacy'),
    url(r'register/$',
        views.register,
        name='register'),
    url(r'tos/$',
        views.tos,
        name='tos'),
)
